version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00"
    reviewers:
      - "thermondo/platform"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    rebase-strategy: disabled
